exports.ICUFee = [
  {
    Billing_Code: "Select",
    Bed_Category: "SELECT BED",
    Room_Rent: 0,
    IP_Fee: 0,
    Emergency_Fee: 0,
  },
  {
    Billing_Code: "DC",
    Bed_Category: "DAY CARE",
    Room_Rent: 4000,
    IP_Fee: 900,
    Emergency_Fee: 1350,
  },
  {
    Billing_Code: "EDCEC",
    Bed_Category: "EXECUTIVE DAY CARE",
    Room_Rent: 4500,
    IP_Fee: 900,
    Emergency_Fee: 1350,
  },
  {
    Billing_Code: "ER1002-A",
    Bed_Category: "EMERGENCY BED CHARGES ( PER TWO HOURS)",
    Room_Rent: 800,
    IP_Fee: "As per Specialty",
    Emergency_Fee: "As per Specialty",
  },
  {
    Billing_Code: "NRICU",
    Bed_Category: "NEURO ICU",
    Room_Rent: 13000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "CTVSIC",
    Bed_Category: "CTVS ICU",
    Room_Rent: 13000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "CCU",
    Bed_Category: "CCU",
    Room_Rent: 13000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "MICU",
    Bed_Category: "MICU",
    Room_Rent: 13000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "SICU",
    Bed_Category: "SICU",
    Room_Rent: 13000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "HDU",
    Bed_Category: "HDU",
    Room_Rent: 11000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "DLSUIT",
    Bed_Category: "DELIVERY SUITE",
    Room_Rent: 12500,
    IP_Fee: 1500,
    Emergency_Fee: 2250,
  },
  {
    Billing_Code: "LDR",
    Bed_Category: "LDR SUITE",
    Room_Rent: 12500,
    IP_Fee: 1500,
    Emergency_Fee: 2250,
  },
  {
    Billing_Code: "NURS",
    Bed_Category: "NURSERY/NICU LEVEL 1",
    Room_Rent: 5500,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "NICU",
    Bed_Category: "NICU LEVEL 2",
    Room_Rent: 7000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "NICU3",
    Bed_Category: "NICU LEVEL 3",
    Room_Rent: 7500,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "PHDU",
    Bed_Category: "PHDU",
    Room_Rent: 7000,
    IP_Fee: 1100,
    Emergency_Fee: 1650,
  },
  {
    Billing_Code: "PIC",
    Bed_Category: "PICU LEVEL1",
    Room_Rent: 7500,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "PIC2",
    Bed_Category: "PICU LEVEL2",
    Room_Rent: 9000,
    IP_Fee: 1400,
    Emergency_Fee: 2100,
  },
  {
    Billing_Code: "CRIBS",
    Bed_Category: "CRIBS",
    Room_Rent: 550,
    IP_Fee: "As per Cat.",
    Emergency_Fee: "As per Cat.",
  },
];
