exports.OBH = [
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 4088,
      Ref_Service_Code: "BD1001",
      Service_Name: "ANTIBODY SCREENING",
      OPD: 250,
      IPD: 250,
      Four_Sharing: 250,
      Twin_Sharing: 250,
      Single_Room: 250,
      Deluxe_Room: 250,
      Suite_Room: 250
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3078,
      Ref_Service_Code: "BD1002",
      Service_Name: "APHERESIS PLATELETS (SCREENING & PROCESSING CHARGES)",
      OPD: 11000,
      IPD: 11000,
      Four_Sharing: 11000,
      Twin_Sharing: 11000,
      Single_Room: 11000,
      Deluxe_Room: 11000,
      Suite_Room: 11000
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3093,
      Ref_Service_Code: "BD1003",
      Service_Name: "CROSS MATCHING CHARGES & BLOOD GROUPING",
      OPD: 600,
      IPD: 600,
      Four_Sharing: 600,
      Twin_Sharing: 600,
      Single_Room: 600,
      Deluxe_Room: 600,
      Suite_Room: 600
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3082,
      Ref_Service_Code: "BD1004",
      Service_Name: "DONOR SCREENING FOR APHERESIS",
      OPD: 600,
      IPD: 600,
      Four_Sharing: 600,
      Twin_Sharing: 600,
      Single_Room: 600,
      Deluxe_Room: 600,
      Suite_Room: 600
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3086,
      Ref_Service_Code: "BD1005",
      Service_Name: "WHOLE BLOOD - PROCESSING CHARGES",
      OPD: 2900,
      IPD: 2900,
      Four_Sharing: 2900,
      Twin_Sharing: 2900,
      Single_Room: 2900,
      Deluxe_Room: 2900,
      Suite_Room: 2900
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3087,
      Ref_Service_Code: "BD1006",
      Service_Name: "FRESH FROZEN PLASMA (PROCESSING CHARGES)",
      OPD: 1600,
      IPD: 1600,
      Four_Sharing: 1600,
      Twin_Sharing: 1600,
      Single_Room: 1600,
      Deluxe_Room: 1600,
      Suite_Room: 1600
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3083,
      Ref_Service_Code: "BD1007",
      Service_Name: "PACKED CELLS (PROCESSING CHARGES)",
      OPD: 2400,
      IPD: 2400,
      Four_Sharing: 2400,
      Twin_Sharing: 2400,
      Single_Room: 2400,
      Deluxe_Room: 2400,
      Suite_Room: 2400
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3092,
      Ref_Service_Code: "BD1009",
      Service_Name: "PLATELET CONCENTRATES (PROCESSING CHARGES)",
      OPD: 1600,
      IPD: 1600,
      Four_Sharing: 1600,
      Twin_Sharing: 1600,
      Single_Room: 1600,
      Deluxe_Room: 1600,
      Suite_Room: 1600
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3211,
      Ref_Service_Code: "BD1010",
      Service_Name: "THERAPEUTIC PHLEBOTOMY",
      OPD: 600,
      IPD: 600,
      Four_Sharing: 600,
      Twin_Sharing: 600,
      Single_Room: 600,
      Deluxe_Room: 600,
      Suite_Room: 600
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3095,
      Ref_Service_Code: "BD1012",
      Service_Name: "SUBSEQUENT PACK",
      OPD: 250,
      IPD: 250,
      Four_Sharing: 250,
      Twin_Sharing: 250,
      Single_Room: 250,
      Deluxe_Room: 250,
      Suite_Room: 250
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3165,
      Ref_Service_Code: "BD1013",
      Service_Name: "THERMOCOL PACKING CHARGES",
      OPD: 100,
      IPD: 100,
      Four_Sharing: 100,
      Twin_Sharing: 100,
      Single_Room: 100,
      Deluxe_Room: 100,
      Suite_Room: 100
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 8489,
      Ref_Service_Code: "BD1015",
      Service_Name: "APHERESIS PLATELETS (PROCESSING CHARGES)",
      OPD: 10400,
      IPD: 10400,
      Four_Sharing: 10400,
      Twin_Sharing: 10400,
      Single_Room: 10400,
      Deluxe_Room: 10400,
      Suite_Room: 10400
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 9987,
      Ref_Service_Code: "BD1017",
      Service_Name: "PLATELET CONCENTRATES (DENGUE)",
      OPD: 400,
      IPD: 400,
      Four_Sharing: 400,
      Twin_Sharing: 400,
      Single_Room: 400,
      Deluxe_Room: 400,
      Suite_Room: 400
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 13755,
      Ref_Service_Code: "BD1019",
      Service_Name: "LEUCOFILTER WITH COMPODOCK COUNTER",
      OPD: 1100,
      IPD: 1100,
      Four_Sharing: 1100,
      Twin_Sharing: 1100,
      Single_Room: 1100,
      Deluxe_Room: 1100,
      Suite_Room: 1100
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 13774,
      Ref_Service_Code: "BD1020",
      Service_Name: "COMPO DOCK COUNTER",
      OPD: 150,
      IPD: 150,
      Four_Sharing: 150,
      Twin_Sharing: 150,
      Single_Room: 150,
      Deluxe_Room: 150,
      Suite_Room: 150
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 18262,
      Ref_Service_Code: "BD1024",
      Service_Name: "CRYOPRECIPITATE",
      OPD: 650,
      IPD: 650,
      Four_Sharing: 650,
      Twin_Sharing: 650,
      Single_Room: 650,
      Deluxe_Room: 650,
      Suite_Room: 650
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 21024,
      Ref_Service_Code: "BD1026",
      Service_Name: "LEUCOTEPLETED PACKED RED CELL(LDPRBC)",
      OPD: 3500,
      IPD: 3500,
      Four_Sharing: 3500,
      Twin_Sharing: 3500,
      Single_Room: 3500,
      Deluxe_Room: 3500,
      Suite_Room: 3500
    },
    {
      Department_Name: "BLOOD BANK",
      Sub_Name: "INVESTIGATION AND PROCEDURES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 21025,
      Ref_Service_Code: "BD1027",
      Service_Name: "TRANSFER BAG (PER UNIT)",
      OPD: 250,
      IPD: 250,
      Four_Sharing: 250,
      Twin_Sharing: 250,
      Single_Room: 250,
      Deluxe_Room: 250,
      Suite_Room: 250
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "EMERGENCY ROOM SERVICE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6122,
      Ref_Service_Code: "ER1001",
      Service_Name: "REGISTRATION CHARGES",
      OPD: 100,
      IPD: 110,
      Four_Sharing: 0,
      Twin_Sharing: 0,
      Single_Room: 0,
      Deluxe_Room: 0,
      Suite_Room: 0
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "EMERGENCY ROOM SERVICE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6123,
      Ref_Service_Code: "ER1002",
      Service_Name: "EMERGENCY BED CHARGES ( PER TWO HOURS)",
      OPD: 800,
      IPD: 800,
      Four_Sharing: 800,
      Twin_Sharing: 800,
      Single_Room: 800,
      Deluxe_Room: 800,
      Suite_Room: 800
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6128,
      Ref_Service_Code: "ER4001",
      Service_Name: "AMBULANCE CHARGES UPTO 5 KM",
      OPD: 1090,
      IPD: 1090,
      Four_Sharing: 1090,
      Twin_Sharing: 1090,
      Single_Room: 1090,
      Deluxe_Room: 1090,
      Suite_Room: 1090
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6129,
      Ref_Service_Code: "ER4002",
      Service_Name: "AMBULANCE CHARGES PER KM",
      OPD: 60,
      IPD: 60,
      Four_Sharing: 60,
      Twin_Sharing: 60,
      Single_Room: 60,
      Deluxe_Room: 60,
      Suite_Room: 60
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6130,
      Ref_Service_Code: "ER4003",
      Service_Name: "DOCTOR CHARGES",
      OPD: 2910,
      IPD: 2910,
      Four_Sharing: 2910,
      Twin_Sharing: 2910,
      Single_Room: 2910,
      Deluxe_Room: 2910,
      Suite_Room: 2910
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6131,
      Ref_Service_Code: "ER4004",
      Service_Name: "NURSE CHARGES",
      OPD: 2910,
      IPD: 2910,
      Four_Sharing: 2910,
      Twin_Sharing: 2910,
      Single_Room: 2910,
      Deluxe_Room: 2910,
      Suite_Room: 2910
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6132,
      Ref_Service_Code: "ER4005",
      Service_Name: "EQUIPMENT CHARGES",
      OPD: 1460,
      IPD: 1460,
      Four_Sharing: 1460,
      Twin_Sharing: 1460,
      Single_Room: 1460,
      Deluxe_Room: 1460,
      Suite_Room: 1460
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6133,
      Ref_Service_Code: "ER4006",
      Service_Name: "OXYGEN/HR IN AMBULANCE",
      OPD: 150,
      IPD: 150,
      Four_Sharing: 150,
      Twin_Sharing: 150,
      Single_Room: 150,
      Deluxe_Room: 150,
      Suite_Room: 150
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6134,
      Ref_Service_Code: "ER4007",
      Service_Name: "AMBULANCE WAITING CHARGES PER HR",
      OPD: 730,
      IPD: 730,
      Four_Sharing: 730,
      Twin_Sharing: 730,
      Single_Room: 730,
      Deluxe_Room: 730,
      Suite_Room: 730
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 8300,
      Ref_Service_Code: "ER4009",
      Service_Name: "ALS AMBULANCE CHARGES UPTO 5 KM",
      OPD: 2180,
      IPD: 2180,
      Four_Sharing: 2180,
      Twin_Sharing: 2180,
      Single_Room: 2180,
      Deluxe_Room: 2180,
      Suite_Room: 2180
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 8301,
      Ref_Service_Code: "ER4010",
      Service_Name: "AMBULANCE ACTIVATION /ADVANCE CHARGES FOR OUTSIDE DELHI-NCR",
      OPD: 2910,
      IPD: 2910,
      Four_Sharing: 2910,
      Twin_Sharing: 2910,
      Single_Room: 2910,
      Deluxe_Room: 2910,
      Suite_Room: 2910
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 8302,
      Ref_Service_Code: "ER4011",
      Service_Name: "DOCTOR CHARGES 100 - 200 KM",
      OPD: 5810,
      IPD: 5810,
      Four_Sharing: 5810,
      Twin_Sharing: 5810,
      Single_Room: 5810,
      Deluxe_Room: 5810,
      Suite_Room: 5810
    },
    {
      Department_Name: "EMERGENCY ROOM",
      Sub_Name: "AMBULANCE",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 8319,
      Ref_Service_Code: "ER4012",
      Service_Name: "DOCTOR CHARGES MORE THAN 200 KM",
      OPD: 8720,
      IPD: 8720,
      Four_Sharing: 8720,
      Twin_Sharing: 8720,
      Single_Room: 8720,
      Deluxe_Room: 8720,
      Suite_Room: 8720
    },
    {
      Department_Name: "MEDICAL ONCOLOGY",
      Sub_Name: "CHEMOTHERAPY BED CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 16335,
      Ref_Service_Code: "MO3001",
      Service_Name: "CHEMOTHERAPY DAYCARE BED CHARGES (0-2 HOURS)",
      OPD: 2200,
      IPD: 2200,
      Four_Sharing: 2200,
      Twin_Sharing: 2200,
      Single_Room: 2200,
      Deluxe_Room: 2200,
      Suite_Room: 2200
    },
    {
      Department_Name: "MEDICAL ONCOLOGY",
      Sub_Name: "CHEMOTHERAPY BED CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 16336,
      Ref_Service_Code: "MO3002",
      Service_Name: "CHEMOTHERAPY DAYCARE BED CHARGES (2-4 HOURS)",
      OPD: 3300,
      IPD: 3300,
      Four_Sharing: 3300,
      Twin_Sharing: 3300,
      Single_Room: 3300,
      Deluxe_Room: 3300,
      Suite_Room: 3300
    },
    {
      Department_Name: "MEDICAL ONCOLOGY",
      Sub_Name: "CHEMOTHERAPY BED CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 16337,
      Ref_Service_Code: "MO3003",
      Service_Name: "CHEMOTHERAPY DAYCARE BED CHARGES (4-8 HOURS)",
      OPD: 3850,
      IPD: 3850,
      Four_Sharing: 3850,
      Twin_Sharing: 3850,
      Single_Room: 3850,
      Deluxe_Room: 3850,
      Suite_Room: 3850
    },
    {
      Department_Name: "MEDICAL ONCOLOGY",
      Sub_Name: "CHEMOTHERAPY BED CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 16338,
      Ref_Service_Code: "MO3004",
      Service_Name: "CHEMOTHERAPY DAYCARE BED CHARGES (ABOVE 8 HOURS)",
      OPD: 5500,
      IPD: 5500,
      Four_Sharing: 5500,
      Twin_Sharing: 5500,
      Single_Room: 5500,
      Deluxe_Room: 5500,
      Suite_Room: 5500
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2291,
      Ref_Service_Code: 2291,
      Service_Name: "BP CHECK",
      OPD: 90,
      IPD: 90,
      Four_Sharing: 90,
      Twin_Sharing: 90,
      Single_Room: 90,
      Deluxe_Room: 90,
      Suite_Room: 90
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2307,
      Ref_Service_Code: 2307,
      Service_Name: "ANGIO FILM /CD",
      OPD: 770,
      IPD: 770,
      Four_Sharing: 770,
      Twin_Sharing: 770,
      Single_Room: 770,
      Deluxe_Room: 770,
      Suite_Room: 770
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 4798,
      Ref_Service_Code: 4798,
      Service_Name: "HARMONIC",
      OPD: 8470,
      IPD: 8470,
      Four_Sharing: 8470,
      Twin_Sharing: 8470,
      Single_Room: 8470,
      Deluxe_Room: 8470,
      Suite_Room: 8470
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 5474,
      Ref_Service_Code: 5474,
      Service_Name: "CD CHARGES FOR CAG",
      OPD: 310,
      IPD: 310,
      Four_Sharing: 310,
      Twin_Sharing: 310,
      Single_Room: 310,
      Deluxe_Room: 310,
      Suite_Room: 310
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 5475,
      Ref_Service_Code: 5475,
      Service_Name: "CD CHARGES FOR PTCA",
      OPD: 310,
      IPD: 310,
      Four_Sharing: 310,
      Twin_Sharing: 310,
      Single_Room: 310,
      Deluxe_Room: 310,
      Suite_Room: 310
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 12773,
      Ref_Service_Code: "BUC",
      Service_Name: "BABY UTILITY CHARGES",
      OPD: 250,
      IPD: 250,
      Four_Sharing: 250,
      Twin_Sharing: 250,
      Single_Room: 250,
      Deluxe_Room: 250,
      Suite_Room: 250
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 19886,
      Ref_Service_Code: "MIS2211",
      Service_Name: "LAPAROSCOPIC LIGASURE BLUNT TIP",
      OPD: 16500,
      IPD: 16500,
      Four_Sharing: 16500,
      Twin_Sharing: 16500,
      Single_Room: 16500,
      Deluxe_Room: 16500,
      Suite_Room: 16500
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MONITORING CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2300,
      Ref_Service_Code: "MS2001",
      Service_Name: "CARDIAC MONITORING < 8 HOURS",
      OPD: 730,
      IPD: 730,
      Four_Sharing: 730,
      Twin_Sharing: 730,
      Single_Room: 730,
      Deluxe_Room: 730,
      Suite_Room: 730
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MONITORING CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2251,
      Ref_Service_Code: "MS2002",
      Service_Name: "CARDIAC MONITORING > 8 HOURS",
      OPD: 1340,
      IPD: 1340,
      Four_Sharing: 1340,
      Twin_Sharing: 1340,
      Single_Room: 1340,
      Deluxe_Room: 1340,
      Suite_Room: 1340
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MONITORING CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6581,
      Ref_Service_Code: "MS2003",
      Service_Name: "IABP monitoring per day",
      OPD: 2420,
      IPD: 2420,
      Four_Sharing: 2420,
      Twin_Sharing: 2420,
      Single_Room: 2420,
      Deluxe_Room: 2420,
      Suite_Room: 2420
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MONITORING CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2559,
      Ref_Service_Code: "MS2004",
      Service_Name: "ICP MONITORING",
      OPD: 3030,
      IPD: 3030,
      Four_Sharing: 3030,
      Twin_Sharing: 3030,
      Single_Room: 3030,
      Deluxe_Room: 3030,
      Suite_Room: 3030
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 5451,
      Ref_Service_Code: "MS3001",
      Service_Name: "ADMINISTRATIVE / MRD CHARGES",
      OPD: 610,
      IPD: 610,
      Four_Sharing: 610,
      Twin_Sharing: 610,
      Single_Room: 610,
      Deluxe_Room: 610,
      Suite_Room: 610
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 5476,
      Ref_Service_Code: "MS3004",
      Service_Name: "CD CHARGES FOR CATH LAB/DSA LAB)",
      OPD: 610,
      IPD: 610,
      Four_Sharing: 610,
      Twin_Sharing: 610,
      Single_Room: 610,
      Deluxe_Room: 610,
      Suite_Room: 610
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3225,
      Ref_Service_Code: "MS3005",
      Service_Name: "EXTRA NURSING CARE (12 HOURS)",
      OPD: 1460,
      IPD: 1460,
      Four_Sharing: 1460,
      Twin_Sharing: 1460,
      Single_Room: 1460,
      Deluxe_Room: 1460,
      Suite_Room: 1460
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2304,
      Ref_Service_Code: "MS3007",
      Service_Name: "INCUBATION",
      OPD: 1090,
      IPD: 1090,
      Four_Sharing: 1090,
      Twin_Sharing: 1090,
      Single_Room: 1090,
      Deluxe_Room: 1090,
      Suite_Room: 1090
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2294,
      Ref_Service_Code: "MS3008",
      Service_Name: "INJECTION CHARGES (IM/IV)",
      OPD: 160,
      IPD: 160,
      Four_Sharing: 160,
      Twin_Sharing: 160,
      Single_Room: 160,
      Deluxe_Room: 160,
      Suite_Room: 160
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3104,
      Ref_Service_Code: "MS3009",
      Service_Name: "MORTUARY SHEET",
      OPD: 430,
      IPD: 430,
      Four_Sharing: 430,
      Twin_Sharing: 430,
      Single_Room: 430,
      Deluxe_Room: 430,
      Suite_Room: 430
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2506,
      Ref_Service_Code: "MS3010",
      Service_Name: "NEBULIZATION (NEW)",
      OPD: 250,
      IPD: 250,
      Four_Sharing: 250,
      Twin_Sharing: 250,
      Single_Room: 250,
      Deluxe_Room: 250,
      Suite_Room: 250
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2505,
      Ref_Service_Code: "MS3011",
      Service_Name: "NEBULIZATION (PER DAY)",
      OPD: 800,
      IPD: 800,
      Four_Sharing: 800,
      Twin_Sharing: 800,
      Single_Room: 800,
      Deluxe_Room: 800,
      Suite_Room: 800
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2250,
      Ref_Service_Code: "MS3012",
      Service_Name: "OXYGEN CHARGE (PER HOUR)",
      OPD: 60,
      IPD: 60,
      Four_Sharing: 60,
      Twin_Sharing: 60,
      Single_Room: 60,
      Deluxe_Room: 60,
      Suite_Room: 60
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 4624,
      Ref_Service_Code: "MS3013",
      Service_Name: "OXYGEN CHARGES PER DAY",
      OPD: 610,
      IPD: 610,
      Four_Sharing: 610,
      Twin_Sharing: 610,
      Single_Room: 610,
      Deluxe_Room: 610,
      Suite_Room: 610
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2308,
      Ref_Service_Code: "MS3014",
      Service_Name: "SYRINGE PUMP / INFUSION PUMP",
      OPD: 490,
      IPD: 490,
      Four_Sharing: 490,
      Twin_Sharing: 490,
      Single_Room: 490,
      Deluxe_Room: 490,
      Suite_Room: 490
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 7274,
      Ref_Service_Code: "MS3016",
      Service_Name: "ABG/ELEC/MET IN WARDS/CRITICAL AREA",
      OPD: 1460,
      IPD: 1460,
      Four_Sharing: 1460,
      Twin_Sharing: 1460,
      Single_Room: 1460,
      Deluxe_Room: 1460,
      Suite_Room: 1460
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 7258,
      Ref_Service_Code: "MS3017",
      Service_Name: "BLOOD SUGAR MONITORING IN WARD/CRITICAL AREA",
      OPD: 130,
      IPD: 130,
      Four_Sharing: 130,
      Twin_Sharing: 130,
      Single_Room: 130,
      Deluxe_Room: 130,
      Suite_Room: 130
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 10153,
      Ref_Service_Code: "MS3023",
      Service_Name: "MORTUARY CHARGES (UP TO 12 HRS)",
      OPD: 1820,
      IPD: 1820,
      Four_Sharing: 1820,
      Twin_Sharing: 1820,
      Single_Room: 1820,
      Deluxe_Room: 1820,
      Suite_Room: 1820
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 10155,
      Ref_Service_Code: "MS3024",
      Service_Name: "MORTUARY CHARGES (AFTER 12 HRS UPTO 24 HRS)",
      OPD: 3630,
      IPD: 3630,
      Four_Sharing: 3630,
      Twin_Sharing: 3630,
      Single_Room: 3630,
      Deluxe_Room: 3630,
      Suite_Room: 3630
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 9632,
      Ref_Service_Code: "MS3025",
      Service_Name: "STEALTH NAVIGATION ( NEURO)",
      OPD: 9900,
      IPD: 9900,
      Four_Sharing: 9900,
      Twin_Sharing: 9900,
      Single_Room: 9900,
      Deluxe_Room: 9900,
      Suite_Room: 9900
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 17800,
      Ref_Service_Code: "MS3028",
      Service_Name: "BIO MEDICAL WASTE (FOR ALL IPD DEPT)",
      OPD: 250,
      IPD: 250,
      Four_Sharing: 250,
      Twin_Sharing: 250,
      Single_Room: 250,
      Deluxe_Room: 250,
      Suite_Room: 250
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6583,
      Ref_Service_Code: "MS4002",
      Service_Name: "laparoscope charges",
      OPD: 4240,
      IPD: 4240,
      Four_Sharing: 4240,
      Twin_Sharing: 4240,
      Single_Room: 4240,
      Deluxe_Room: 4240,
      Suite_Room: 4240
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6584,
      Ref_Service_Code: "MS4003",
      Service_Name: "c arm",
      OPD: 1460,
      IPD: 1460,
      Four_Sharing: 1460,
      Twin_Sharing: 1460,
      Single_Room: 1460,
      Deluxe_Room: 1460,
      Suite_Room: 1460
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2377,
      Ref_Service_Code: "MS4004",
      Service_Name: "DVT PUMP/ PNEUMATIC",
      OPD: 730,
      IPD: 730,
      Four_Sharing: 730,
      Twin_Sharing: 730,
      Single_Room: 730,
      Deluxe_Room: 730,
      Suite_Room: 730
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6585,
      Ref_Service_Code: "MS4005",
      Service_Name: "cpap per day",
      OPD: 3030,
      IPD: 3030,
      Four_Sharing: 3030,
      Twin_Sharing: 3030,
      Single_Room: 3030,
      Deluxe_Room: 3030,
      Suite_Room: 3030
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2302,
      Ref_Service_Code: "MS4006",
      Service_Name: "BIPAP CHARGES (PER DAY)",
      OPD: 3030,
      IPD: 3030,
      Four_Sharing: 3030,
      Twin_Sharing: 3030,
      Single_Room: 3030,
      Deluxe_Room: 3030,
      Suite_Room: 3030
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 6586,
      Ref_Service_Code: "MS4007",
      Service_Name: "Hysteroscope/cystoscope/ureteroscope/endoscope",
      OPD: 1460,
      IPD: 1460,
      Four_Sharing: 1460,
      Twin_Sharing: 1460,
      Single_Room: 1460,
      Deluxe_Room: 1460,
      Suite_Room: 1460
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 7278,
      Ref_Service_Code: "MS4008",
      Service_Name: "NEURO ENDOSCOPE",
      OPD: 12100,
      IPD: 12100,
      Four_Sharing: 12100,
      Twin_Sharing: 12100,
      Single_Room: 12100,
      Deluxe_Room: 12100,
      Suite_Room: 12100
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2357,
      Ref_Service_Code: "MS4009",
      Service_Name: "VENTILATOR CHARGES (LESS THEN 8 HOURS)",
      OPD: 1820,
      IPD: 1820,
      Four_Sharing: 1820,
      Twin_Sharing: 1820,
      Single_Room: 1820,
      Deluxe_Room: 1820,
      Suite_Room: 1820
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 7279,
      Ref_Service_Code: "MS4010",
      Service_Name: "VENTILATOR CHARGES(MORE THEN 8 HOURS)",
      OPD: 4240,
      IPD: 4240,
      Four_Sharing: 4240,
      Twin_Sharing: 4240,
      Single_Room: 4240,
      Deluxe_Room: 4240,
      Suite_Room: 4240
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 5432,
      Ref_Service_Code: "MS4011",
      Service_Name: "VENTILATOR CHARGES - STAND BY (RESERVED)",
      OPD: 1820,
      IPD: 1820,
      Four_Sharing: 1820,
      Twin_Sharing: 1820,
      Single_Room: 1820,
      Deluxe_Room: 1820,
      Suite_Room: 1820
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 9871,
      Ref_Service_Code: "MS4012",
      Service_Name: "COMPUTER NAVIGATION (ORTHO)",
      OPD: 4240,
      IPD: 4240,
      Four_Sharing: 4240,
      Twin_Sharing: 4240,
      Single_Room: 4240,
      Deluxe_Room: 4240,
      Suite_Room: 4240
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 12707,
      Ref_Service_Code: "MS4014",
      Service_Name: "CORDLESS ULTRASONIC DEVICE",
      OPD: 12100,
      IPD: 12100,
      Four_Sharing: 12100,
      Twin_Sharing: 12100,
      Single_Room: 12100,
      Deluxe_Room: 12100,
      Suite_Room: 12100
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 12709,
      Ref_Service_Code: "MS4016",
      Service_Name: "MORCELLATOR (LARGE SPECIMEN)",
      OPD: 9680,
      IPD: 9680,
      Four_Sharing: 9680,
      Twin_Sharing: 9680,
      Single_Room: 9680,
      Deluxe_Room: 9680,
      Suite_Room: 9680
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 12740,
      Ref_Service_Code: "MS4017",
      Service_Name: "ADVANCE LIGASURE",
      OPD: 12100,
      IPD: 12100,
      Four_Sharing: 12100,
      Twin_Sharing: 12100,
      Single_Room: 12100,
      Deluxe_Room: 12100,
      Suite_Room: 12100
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 12788,
      Ref_Service_Code: "MS4018",
      Service_Name: "ENDOSCOPE (UROLOGY)",
      OPD: 4240,
      IPD: 4240,
      Four_Sharing: 4240,
      Twin_Sharing: 4240,
      Single_Room: 4240,
      Deluxe_Room: 4240,
      Suite_Room: 4240
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "EQUIPMENT CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 14097,
      Ref_Service_Code: "MS4019",
      Service_Name: "HARMONIC HANDPIECE",
      OPD: 2420,
      IPD: 2420,
      Four_Sharing: 2420,
      Twin_Sharing: 2420,
      Single_Room: 2420,
      Deluxe_Room: 2420,
      Suite_Room: 2420
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 19917,
      Ref_Service_Code: "MS4035",
      Service_Name: "AEROGEN NEBULIZATION",
      OPD: 330,
      IPD: 330,
      Four_Sharing: 330,
      Twin_Sharing: 330,
      Single_Room: 330,
      Deluxe_Room: 330,
      Suite_Room: 330
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 12080,
      Ref_Service_Code: "MS5048",
      Service_Name: "INFUSION CHARGES",
      OPD: 5870,
      IPD: 5870,
      Four_Sharing: 5870,
      Twin_Sharing: 5870,
      Single_Room: 5870,
      Deluxe_Room: 5870,
      Suite_Room: 5870
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 18973,
      Ref_Service_Code: "NP2017",
      Service_Name: "HOSPITAL UNIFORM CHARGES",
      OPD: 1100,
      IPD: 1100,
      Four_Sharing: 1100,
      Twin_Sharing: 1100,
      Single_Room: 1100,
      Deluxe_Room: 1100,
      Suite_Room: 1100
    },
    {
      Department_Name: "MISCELLANEOUS SERVICES",
      Sub_Name: "MISCELLANEOUS SERVICES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 12739,
      Ref_Service_Code: "RC1006",
      Service_Name: "HUNTLEIGH ALPHA BED (PER DAY)",
      OPD: 370,
      IPD: 370,
      Four_Sharing: 370,
      Twin_Sharing: 370,
      Single_Room: 370,
      Deluxe_Room: 370,
      Suite_Room: 370
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3202,
      Ref_Service_Code: "RD2061",
      Service_Name: "CT-CONTRAST-CHARGES NON-IONIC 100 CC",
      OPD: 2550,
      IPD: 2550,
      Four_Sharing: 2550,
      Twin_Sharing: 2550,
      Single_Room: 2550,
      Deluxe_Room: 2550,
      Suite_Room: 2550
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 33,
      Ref_Service_Code: "RD2062",
      Service_Name: "CT-CONTRAST-CHARGES NON-IONIC 50CC (300MG)",
      OPD: 1280,
      IPD: 1280,
      Four_Sharing: 1280,
      Twin_Sharing: 1280,
      Single_Room: 1280,
      Deluxe_Room: 1280,
      Suite_Room: 1280
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2931,
      Ref_Service_Code: "RD2063",
      Service_Name: "CT-CONTRAST CHARGES -VISIPAQUE",
      OPD: 3850,
      IPD: 3850,
      Four_Sharing: 3850,
      Twin_Sharing: 3850,
      Single_Room: 3850,
      Deluxe_Room: 3850,
      Suite_Room: 3850
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 7336,
      Ref_Service_Code: "RD2064",
      Service_Name: "CT-CD CHARGE",
      OPD: 330,
      IPD: 330,
      Four_Sharing: 330,
      Twin_Sharing: 330,
      Single_Room: 330,
      Deluxe_Room: 330,
      Suite_Room: 330
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 13803,
      Ref_Service_Code: "RD2093",
      Service_Name: "CT - EXTRA FILM",
      OPD: 470,
      IPD: 470,
      Four_Sharing: 470,
      Twin_Sharing: 470,
      Single_Room: 470,
      Deluxe_Room: 470,
      Suite_Room: 470
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 81,
      Ref_Service_Code: "RD4035",
      Service_Name: "MRI CONTRAST CHARGES",
      OPD: 4400,
      IPD: 4400,
      Four_Sharing: 4400,
      Twin_Sharing: 4400,
      Single_Room: 4400,
      Deluxe_Room: 4400,
      Suite_Room: 4400
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 7272,
      Ref_Service_Code: "RD4036",
      Service_Name: "MRI CD/DVD CHARGES",
      OPD: 440,
      IPD: 440,
      Four_Sharing: 440,
      Twin_Sharing: 440,
      Single_Room: 440,
      Deluxe_Room: 440,
      Suite_Room: 440
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 72,
      Ref_Service_Code: "RD4037",
      Service_Name: "MRI (EXTRA FILM)",
      OPD: 490,
      IPD: 490,
      Four_Sharing: 490,
      Twin_Sharing: 490,
      Single_Room: 490,
      Deluxe_Room: 490,
      Suite_Room: 490
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2909,
      Ref_Service_Code: "RD5056",
      Service_Name: "ULTRA SOUND EXTRA FILM",
      OPD: 280,
      IPD: 280,
      Four_Sharing: 280,
      Twin_Sharing: 280,
      Single_Room: 280,
      Deluxe_Room: 280,
      Suite_Room: 280
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2781,
      Ref_Service_Code: "RD6049",
      Service_Name: "X-RAY IVP + MCU FILM",
      OPD: 4550,
      IPD: 4550,
      Four_Sharing: 4550,
      Twin_Sharing: 4550,
      Single_Room: 4550,
      Deluxe_Room: 4550,
      Suite_Room: 4550
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 2702,
      Ref_Service_Code: "RD6116",
      Service_Name: "X-RAY EXTRA FILM",
      OPD: 170,
      IPD: 170,
      Four_Sharing: 170,
      Twin_Sharing: 170,
      Single_Room: 170,
      Deluxe_Room: 170,
      Suite_Room: 170
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 3161,
      Ref_Service_Code: "RD6117",
      Service_Name: "X-RAY CD CHARGES",
      OPD: 170,
      IPD: 170,
      Four_Sharing: 170,
      Twin_Sharing: 170,
      Single_Room: 170,
      Deluxe_Room: 170,
      Suite_Room: 170
    },
    {
      Department_Name: "RADIOLOGY",
      Sub_Name: "OTHER CHARGES",
      Department_Type: "OTHER BILLING HEADS",
      ServiceId: 101,
      Ref_Service_Code: "RD7001",
      Service_Name: "ANAESTHESIA/SEDATION FOR RADIOLOGY",
      OPD: 1650,
      IPD: 1650,
      Four_Sharing: 1650,
      Twin_Sharing: 1650,
      Single_Room: 1650,
      Deluxe_Room: 1650,
      Suite_Room: 1650
    }
  ]